# Generated by Django 4.0.6 on 2023-10-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='bonus',
            new_name='bonus_1',
        ),
        migrations.AddField(
            model_name='trade',
            name='bonus_2',
            field=models.CharField(choices=[('HP Regen', 'HP Regen'), ('Mana Regen', 'Mana Regen'), ('Potion Bonus', 'Potion Bonus'), ('Leech', 'Leech'), ('Money Find', 'Money Find'), ('Thorns', 'Thorns'), ('Omni Resist', 'Omni Resist'), ('Fortified', 'Fortified'), ('Empowered', 'Empowered'), ('Crit Chance', 'Crit Chance'), ('Accuracy', 'Accuracy'), ('Block %', 'Block %')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='bonus',
            field=models.TextField(choices=[("['HP Regen', 'Mana Regen', 'Potion Bonus', 'Leech', 'Money Find', 'Thorns', 'Omni Resist', 'Fortified', 'Empowered', 'Crit Chance']", 'Magic Bonuses'), ("['HP Regen', 'Mana Regen', 'Potion Bonus', 'Leech', 'Money Find', 'Thorns', 'Omni Resist', 'Fortified', 'Empowered', 'Accuracy']", 'Distance Bonuses'), ("['HP Regen', 'Mana Regen', 'Potion Bonus', 'Leech', 'Money Find', 'Thorns', 'Omni Resist', 'Fortified', 'Empowered', 'Block %']", 'Mele Bonuses')], max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='secondary_stat',
            field=models.TextField(choices=[("['Spirit', 'Defense', 'Magic']", 'Secondary and Magic'), ("['Spirit', 'Defense', 'Distance']", 'Secondary and Distance'), ("['Spirit', 'Defense', 'Mele']", 'Secondary and Mele')], max_length=40),
        ),
        migrations.AlterField(
            model_name='trade',
            name='secondary_stat',
            field=models.CharField(choices=[("['Spirit', 'Defense', 'Magic']", 'Secondary and Magic'), ("['Spirit', 'Defense', 'Distance']", 'Secondary and Distance'), ("['Spirit', 'Defense', 'Mele']", 'Secondary and Mele')], max_length=40),
        ),
    ]
