# Generated by Django 4.0.6 on 2023-10-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_bonus_trade_bonus_1_trade_bonus_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='secondary_stat',
            field=models.CharField(choices=[('Spirit', 'Spirit'), ('Defense', 'Defense'), ('Magic', 'Magic'), ('Distance', 'Distance'), ('Melee', 'Melee')], max_length=40),
        ),
    ]
