# Generated by Django 4.0.6 on 2023-11-30 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_item_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slot',
            field=models.CharField(choices=[('Helmet', 'Helmet'), ('Chest', 'Chest'), ('Gloves', 'Gloves'), ('Boots', 'Boots')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stamina',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='armour',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='bonus',
            field=models.TextField(choices=[("['HP Regen', 'Mana Regen', 'Potion Bonus', 'Leech', 'Money Find', 'Thorns', 'Omni Resist', 'Fortified', 'Empowered', 'Crit Chance']", 'Magic Bonuses'), ("['HP Regen', 'Mana Regen', 'Potion Bonus', 'Leech', 'Money Find', 'Thorns', 'Omni Resist', 'Fortified', 'Empowered', 'Accuracy']", 'Distance Bonuses'), ("['HP Regen', 'Mana Regen', 'Potion Bonus', 'Leech', 'Money Find', 'Thorns', 'Omni Resist', 'Fortified', 'Empowered', 'Block %']", 'Melee Bonuses')], max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_amount_primary_stat',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='max_amount_secondary_stat',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='secondary_stat',
            field=models.TextField(choices=[("['Spirit', 'Defense', 'Magic']", 'Secondary and Magic'), ("['Spirit', 'Defense', 'Distance']", 'Secondary and Distance'), ("['Spirit', 'Defense', 'Melee']", 'Secondary and Melee')], max_length=40),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
