# Generated by Django 4.0.6 on 2023-11-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_slot_item_stamina_trade_date_alter_item_armour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slot',
            field=models.CharField(choices=[('Helmet', 'Helmet'), ('Chest', 'Chest'), ('Gloves', 'Gloves'), ('Boots', 'Boots')], max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='stamina',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
